### ISSUE TITLE
本地数据库连接问题

### ISSUE THREAD

**Issue by likinabs** [Cheung0-bit/supermarket-manage-system#2]
1、修改application-dev切换本地数据库时报错无法启动，要怎么解决
Description:
Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.
Reason: Failed to determine a suitable driver class
2、大神没看到mangoDB，是不是没有使用

**Comment by Cheung0-bit** [comment]
1. 你试试在启动类上加`@SpringBootApplication(exclude={DataSourceAutoConfigure.class})`排除数据源自动配置试试呢
2. MongoDB可以用于动态加载侧边栏目录 这里我应该是将不同角色的目录都写死了 记不清了hh

**Comment by ywq216221** [comment]
哥，我在启动类上加了@SpringBootApplication(exclude={DataSourceAutoConfigure.class})但是还是报错啊。如果你方便的话，可以远程指导我吗？拜托啦！拜托啦！请加我的微信yang1022875776

**Comment by Cheung0-bit** [comment]
***@***.***(exclude={DataSourceAutoConfigure.class})的作用仅仅是排除了数据源的自动加载。我想问题应该是maven打包工具版本迭代，导致了配置文件没有被打包到classpath下面，导致SpringBoot程序没有正确读取并加载配置。你可以尝试编辑pom文件，手动将配置文件打包。如果还有问题，可以联系我微信，cheung0-bit




Entic_E
***@***.***

南京信息工程大学


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Cheung0-bit/supermarket-manage-system"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月22日(星期三) 晚上9:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Cheung0-bit/supermarket-manage-system] 本地数据库连接问题 (Issue #2)





 
***@***.***(exclude={DataSourceAutoConfigure.class})但是还是报错啊。如果你方便的话，可以远程指导我吗？拜托啦！拜托啦！请加我的微信yang1022875776
